### ISSUE TITLE
UserWarning: Argument interpolation should be of type interpolationmode

### ISSUE THREAD

**Issue by WendongZh** [wvangansbeke/Revisiting-Contrastive-SSL#1]
Brilliant work! 

However when I run you command "sh scripts/ours_coco_200ep.sh", It print warning as follows:

......../torchvision\transforms\transforms.py:365: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.

It seems that you use int number in the resize function of pytorch transforms and I guess it may not influence the performance , but I fail to locate the bug. So would you mind to give some suggestions?

Besides I use pytorch=1.8.0 with torchvision=0.9.0

Thanks~

**Comment by wvangansbeke** [comment]
Hi @WendongZh,

Thank you for your interest.

The code was run with Pytorch 1.6. You can find all the packages in the `environment.yml` file btw. The interpolation mode for the resizing function in the augmentations or architecture probably causes the warning with the recent Pytorch version. I don't think it will change much, but you can modify it if you want.
