### ISSUE TITLE
How to draw GradCAM without classifier?

### ISSUE THREAD

**Issue by pansanity666** [wvangansbeke/Revisiting-Contrastive-SSL#2]
Hi, 
May I ask how did you get the GradCAM figure without classifier for these unsupervised methods? 

Thx,

**Comment by wvangansbeke** [comment]
Hi @pansanity666,

I believe you are referring to figure 6. We only finetune 1 linear layer (classifier) on top of the frozen representations. Now, we can visualize the class activation maps exactly the same as in the supervised setting.
